version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    branches:
          only:
            - master
    steps:
      - run:
          name: Build React App
          command: |
             npm run build
      - run:
          name: Install LFTP
          command: |
             apt-get update -qq && apt-get install -y -qq sshpass rsync;
      - run:
          name: Send Via SSHPASS
          command: |
            cd build/
            ls
            sshpass -V
            export SSHPASS=$USER_PASS
            sshpass -e rsync -r --omit-dir-times -e "ssh -o StrictHostKeyChecking=no" . ermineadmin@ssh.dhosting.pl:/home/klient.dhosting.pl/ermineadmin/react-gitlab.ermine.pl/X